# Generated by Django 5.2.7 on 2025-12-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nyxboard", "0009_healthcheck_data_alter_healthcheck_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcheck",
            name="check_type",
            field=models.CharField(
                choices=[
                    ("http", "HTTP"),
                    ("json-http", "JSON-HTTP"),
                    ("tcp", "TCP"),
                    ("ping", "Ping"),
                    ("dns", "DNS"),
                    ("smtp", "SMTP"),
                    ("imap", "IMAP"),
                    ("json-metrics", "JSON Metrics"),
                    ("custom", "Custom"),
                ],
                default="http",
                max_length=20,
                verbose_name="Check Type",
            ),
        ),
    ]
