# Generated by Django 5.2.7 on 2026-08-31 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nyxboard", "0010_alter_healthcheck_check_type"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS check_notification_state (
                            check_id INTEGER PRIMARY KEY
                                REFERENCES health_check(id) ON DELETE CASCADE,
                            failure_count INTEGER NOT NULL DEFAULT 0,
                            last_attempt_count INTEGER NOT NULL DEFAULT 0,
                            last_immediate_at INTEGER NOT NULL DEFAULT 0
                        )
                    """,
                    reverse_sql="DROP TABLE IF EXISTS check_notification_state",
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name="CheckNotificationState",
                    fields=[
                        (
                            "health_check",
                            models.OneToOneField(
                                db_column="check_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                primary_key=True,
                                related_name="notification_state",
                                serialize=False,
                                to="nyxboard.healthcheck",
                            ),
                        ),
                        (
                            "failure_count",
                            models.PositiveIntegerField(default=0),
                        ),
                        (
                            "last_attempt_count",
                            models.PositiveIntegerField(default=0),
                        ),
                        (
                            "last_immediate_at",
                            models.PositiveBigIntegerField(default=0),
                        ),
                    ],
                    options={"db_table": "check_notification_state"},
                )
            ],
        )
    ]
