# Generated by Django 5.2 on 2025-04-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nyxboard", "0002_remove_service_data_service_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthcheck",
            name="data",
        ),
        migrations.AddField(
            model_name="healthcheck",
            name="check_type",
            field=models.CharField(
                choices=[
                    ("http", "HTTP"),
                    ("tcp", "TCP"),
                    ("ping", "Ping"),
                    ("dns", "DNS"),
                    ("custom", "Custom"),
                ],
                default="http",
                max_length=20,
                verbose_name="Check Type",
            ),
        ),
        migrations.AddField(
            model_name="healthcheck",
            name="url",
            field=models.URLField(default="", max_length=512, verbose_name="URL"),
            preserve_default=False,
        ),
    ]
