# Generated by Django 5.2 on 2025-04-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nyxboard", "0003_remove_healthcheck_data_healthcheck_check_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcheck",
            name="check_interval",
            field=models.IntegerField(
                choices=[
                    (30, "30 seconds"),
                    (60, "1 minute"),
                    (300, "5 minutes"),
                    (900, "15 minutes"),
                    (1800, "30 minutes"),
                    (3600, "1 hour"),
                    (86400, "1 day"),
                ],
                default=300,
                help_text="How often this health check should be performed",
                verbose_name="Check Interval",
            ),
        ),
    ]
