fqdn: "*"  # Allow all hosts for local network access
deploy_environment: "macmini"
username: "nyxmon"
host_name: macmini
django_settings_module: "config.settings.macos"  # Use macOS settings (no SSL redirect)
# app_port is defined in vars.yml as 10017